###########################################################################
##  Nagoya Institute of Technology's HTS Engine                          ##
##  Integrated in the bellbird tree                                      ##
##  Peter M Drysdale (drysdalepete@gmail.com)                            ##
###########################################################################
TOP=../..
DIRNAME=src/nitechvoice
H = nitech_hidden 

SRCS = nitech_mlpg.c nitech_model.c nitech_tree.c nitech_vocoder.c nitech_engine.c

OBJS = $(SRCS:.c=.o) 

FILES=Makefile $(SRCS) $(H)

LOCAL_INCLUDES =

LIBNAME = bellbird

ALL = 

include $(TOP)/config/common_make_rules


