###########################################################################
##  Some common synthesis routines                                       ##
##  Integrated in the bellbird tree                                      ##
##  Peter M Drysdale (drysdalepete@gmail.com)                            ##
###########################################################################
TOP=../..
DIRNAME=src/commonsynth
H = 

SRCS = HTS_misc.c bell_driver.c

OBJS = $(SRCS:.c=.o) 

FILES=Makefile $(SRCS) $(H)

LOCAL_INCLUDES =

LIBNAME = bellbird

ALL = 

include $(TOP)/config/common_make_rules


