#ifndef _BELL_FF_SYM_H_
#define _BELL_FF_SYM_H_

// These are compact forms of featfunc symbols
// Using these definitions improves performance of internal_ff
// The values themselves are irrelevant it is only required they are unique
// and a single byte
// The value \x00 is unavailable as it is the string terminator

#define PH_VC "\x01"
#define PH_VLNG "\x02"
#define PH_VHEIGHT "\x03"
#define PH_VFRONT "\x04"
#define PH_VRND "\x05"
#define PH_CTYPE "\x06"
#define PH_CPLACE "\x07"
#define PH_CVOX "\x08"

#define LISP_CG_DURATION "\x10"
#define LISP_CG_STATE_POS "\x11"
#define LISP_CG_STATE_PLACE "\x12"
#define LISP_CG_STATE_INDEX "\x13"
#define LISP_CG_STATE_RINDEX "\x14"
#define LISP_CG_PHONE_PLACE "\x15"
#define LISP_CG_PHONE_INDEX "\x16"
#define LISP_CG_PHONE_RINDEX "\x17"

#define LISP_CG_POSITION_IN_PHRASEP "\x20"
#define LISP_CG_FIND_PHRASE_NUMBER "\x21"
#define LISP_IS_PAU "\x22"

#define WORD_NUMSYLS "\x30"
#define WORD_BREAK "\x31"
#define WORD_PUNC "\x32"
#define SSYL_IN "\x33"
#define SSYL_OUT "\x34"
#define SYL_IN "\x35"
#define SYL_OUT "\x36"
#define SYL_BREAK "\x37"
#define LISP_CG_BREAK "\x38"
#define OLD_SYL_BREAK "\x39"
#define SYL_ONSETSIZE "\x3a"
#define SYL_CODASIZE "\x3b"
#define ACCENTED "\x3c"
#define ASYL_IN "\x3d"
#define ASYL_OUT "\x3e"
#define LISP_CODA_FRIC "\x3f"
#define LISP_ONSET_FRIC "\x40"
#define LISP_CODA_STOP "\x41"
#define LISP_ONSET_STOP "\x42"
#define LISP_CODA_NASAL "\x43"
#define LISP_ONSET_NASAL "\x44"
#define LISP_CODA_GLIDE "\x45"
#define LISP_ONSET_GLIDE "\x46"
#define SEG_ONSETCODA "\x47"
#define POS_IN_SYL "\x48"
#define POSITION_TYPE "\x49"
#define SUB_PHRASES "\x4a"
#define LAST_ACCENT "\x4b"
#define NEXT_ACCENT "\x4c"
#define SYL_FINAL "\x4d"
#define SEGMENT_DURATION "\x4e"
#define LISP_CG_SYL_RATIO "\x4f"
#define LISP_CG_PHRASE_RATIO "\x50"
#define LISP_CG_SYLS_IN_PHRASE "\x51"
#define POS_IN_PHRASE "\x52"
#define POS_IN_WORD "\x53"
#define SYLLABLE_DURATION "\x54"
#define SYL_VOWEL "\x55"
#define SYL_NUMPHONES "\x56"

// en_US HTS symbols
#define LISP_DISTANCE_TO_P_STRESS "\x60"
#define LISP_DISTANCE_TO_N_STRESS "\x61"
#define LISP_DISTANCE_TO_P_ACCENT "\x62"
#define LISP_DISTANCE_TO_N_ACCENT "\x63"
#define WORDS_OUT "\x64"
#define HTS_CONTENT_WORDS_IN "\x65"
#define HTS_CONTENT_WORDS_OUT "\x66"
#define LISP_DISTANCE_TO_P_CONTENT "\x67"
#define LISP_DISTANCE_TO_N_CONTENT "\x68"
#define LISP_NUM_SYLS_IN_PHRASE "\x69"
#define LISP_NUM_WORDS_IN_PHRASE "\x6a"
#define LISP_TOTAL_SYLS "\x6b"
#define LISP_TOTAL_WORDS "\x6c"
#define LISP_TOTAL_PHRASES "\x6d"

// en_US symbols
#define GPOS "\x70"
#define NUM_DIGITS "\x71"
#define MONTH_RANGE "\x72"
#define TOKEN_POS_GUESS "\x73"
#define CONTENT_WORDS_IN "\x74"
#define CONTENT_WORDS_OUT "\x75"
#define LISP_CG_CONTENT_WORDS_IN_PHRASE "\x76"

#endif
